apiVersion: v1
kind: Service
metadata:
  name: MyApp
  namespace: default
  labels:
    app: MyApp
spec:
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 32609
    target-port: 80
  selector:
    app: MyApp
  type: LoadBalancer