apiVersion: v1
kind: Service
metadata:
  name: App
  namespace: default
  labels:
    app: App
spec:
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 32609
    target-port: 80
  selector:
    app: App
  type: LoadBalancer